version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: yourdbname
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
  web:
    build: ./django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_app:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build: ./vue_app
    ports:
      - "8080:8080"
    depends_on:
      - web
